package me.funso.angtowerdefense.packet;

public enum PacketOpcode {
	ALERT, 
	REQ_LOGIN, RES_LOGIN, 
	REQ_JOIN, RES_JOIN, 
	REQ_START_GAME, RES_START_GAME, 
	REQ_SAVE_GAME, RES_SAVE_GAME, 
	REQ_LOAD_GAME, RES_LOAD_GAME, 
	REQ_LOAD_MAP, RES_LOAD_MAP, 
	REQ_MONSTER_INFO, RES_MONSTER_INFO,
	REQ_TOWER_INFO, RES_TOWER_INFO,
	SPAWN_MONSTER, INSTALL_TOWER, 
	REQ_UPGRADE, RES_UPGRADE, 
	REQ_SKILL, RES_SKILL
}
