package me.funso.angtowerdefense.packet;

public enum PacketOpcode {
	ALERT, REQ_LOGIN, RES_LOGIN, REQ_JOIN, RES_JOIN, REQSTART, RESSTART, REQSAVE, RESSAVE, REQLOAD, RESLOAD, SPAWNMONSTER, INSTALLTOWER, REQUPGRADE, RESUPGRADE, REQSKILL, RESSKILL
}
