package me.funso.angtowerdefense;

public enum PacketOpcode {
	ALERT, REQLOGIN, RESLOGIN, REQJOIN, RESJOIN, REQSTART, RESSTART, REQSAVE, RESSAVE, REQLOAD, RESLOAD, SPAWNMONSTER, INSTALLTOWER, REQUPGRADE, RESUPGRADE, REQSKILL, RESSKILL
}
